### ISSUE TITLE
create social media link with image and icon

### ISSUE THREAD

**Issue by marianzburlea** [wowdop/can-you-do-it#6]
Create social media link with icon and image as background.

Colour list with hex values:
* instagram: #F77737
* facebook: #4267B2
* twitter: #1DA1F2
* YouTube: #FF0000

Check https://icon-sets.iconify.design/icomoon-free/instagram/ for more icons
Check https://brandpalettes.com/youtube-color-codes/ for more colours

**Comment by Vladislava05** [comment]
I wanna do it
